### ISSUE TITLE
Dynamic Link Component

### ISSUE THREAD

**Issue by mbwatson** [stagecc/bdc3-website-public#132]
there are two link components &mdash; `Link` (from @reach/router) and `ExternalLink` (which adds the little icon suffix and prompts the user with a confirmation dialog about heading to a non-dot-gov site). this means the developer needs to know the URL beforehand to determine which link component to use, which if of course not ideal.

i'm proposing a dynamic catch-all `Link` component that determines whether the linked-to URL is an internal or an external link (regex match), and return the internal link or the external link component.

@scrummish i've started this on this [feature/dynamic-link-component](https://github.com/stagecc/bdc3-website-public/tree/feature/dynamic-link-component) branch. you'll see two commits &mdash; one that adds the component, and another commit that implements the new `Link` component on a single view.

can you take on swapping out `ExternalLink` components for this new `Link` component? grep and sed should make this a trivial task. but we want to be careful not to mess up other link-related things, like buttons.

**Comment by mbwatson** [comment]
after some simmering on this, i realized we may want to move the dot-gov URL checking regex logic into the `Link` component itself, as it currently just checks if the link starts with `http`.

**Comment by scrummish** [comment]
all links have been updated

**Comment by mbwatson** [comment]
nice!

**Comment by mbwatson** [comment]
i've added a component to process event markdown content with react-markdown. @scrummish check out the recent additions to the [feature/dynamic-link-component branch](https://github.com/stagecc/bdc3-website-public/tree/feature/dynamic-link-component)/
