### ISSUE TITLE
past events dont automatically archive

### ISSUE THREAD

**Issue by scrummish** [stagecc/bdc3-website-public#134]
bdc3 needs to rebuild in order for past events to archive themselves

**Comment by mbwatson** [comment]
his might be something we're stuck with if using templated SSG pages for the events. i see a couple of options: 1. auto-build the site regularly (probably nightly), or 2. generate the events pages at runtime.

@scrummish what other possible options do you see?

**Comment by scrummish** [comment]
@mbwatson sorry for the late response. This was fixed a while ago
