### ISSUE TITLE
Call the Metadata Service (MDS) to populate study data table

### ISSUE THREAD

**Issue by mbwatson** [stagecc/bdc3-website-public#135]
The Discovery page appears to be live in production and have BioLINCC study metadata.

To keep [our data table](https://staging.biodatacatalyst.nhlbi.nih.gov/resources/data/studies/) up-to-date. we will need to access that MDS API to retrieve the study metadata. Contact Gen3 devs for this information.

**Comment by mbwatson** [comment]
the illustrious @jcheadle-rti has written a wonderful python script to fetch the study data from the MDS API.
see our fork of this [here](https://github.com/stagecc/bdc3_data_table_autoupdate). executing this scrip using [this github action](https://github.com/stagecc/bdc3_data_table_autoupdate/blob/main/.github/workflows/update_data_table.yml) fetches the data and massages it into the desired form for our application to consume, and makes a commit that adds the study JSON to the `./output` directory.

now the question remains: how do we use this in the BDC website? we have a few options:

1. rework the github action in our fork that runs the script to make a commit into _this_ repo at the location our application already looks for the study data, [src/data/studies](https://github.com/stagecc/bdc3-website-public/tree/master/src/data/studies).
2. use the fork's script as a guide to handle the data fetching and data massaging from this application at runtime.
3. use the fork's script as a guide to handle the data fetching and data massaging from this application at build time.

1 is clearly the lighter lift, but there would still be details to suss out, such as _on what branch does it make the commit?_, and likely more. 2 and 3 are great options, but may require a few additional development cycles.

**Comment by scrummish** [comment]
Hi @stephsuber,

So the old files had the following data in the studies table 

Name:
Short Name:
Description:
Accession:
Type: 
Link: 
Network:
Responsible Party:
Other Information:

The new studies files only have this information 

Accession: 
Cohort Abbreviation: 
Name:
Description:
Consent Code:
Consent Short:
Subject Count: 

If there are any fields that are no longer present that we still need please let me know so we can figure out a way to automate this.

Thank you

**Comment by mbwatson** [comment]
closing for #242 242
