### ISSUE TITLE
Website text edits

### ISSUE THREAD

**Issue by pkrenci** [stagecc/bdc3-website-public#148]
Hi, here are some requested edits for the Cloud Credits webpage:

1) Update the title tag to "Cloud Costs and Credits" to match the text on the top of the page

2) In this sentence:
"Others may use the $500 in cloud credits to test and evaluate BioData Catalyst..."

add 4 words so it says:
"Others, including NIH intramural researchers, may use the $500 in cloud credits to test and evaluate BioData Catalyst..."

3) In this sentence:
"Use these resources to understand and estimate cloud costs..."
 
add an anchor tag to the phrase "Use these resources" which links to the section lower on the page titled "Understanding and Estimating Cloud Costs".

4) In the section titled "Understanding and Estimating Cloud Costs", add a new link at the bottom called "Estimate and Manage Your Cloud Costs (BioData Catalyst powered by Seven Bridges" that links to:
https://sb-biodatacatalyst.readme.io/docs/estimate-and-manage-your-cloud-costs

5) After this sentence:
"Cloud Credit Program requests will be reviewed and decided as soon as possible."

add these 2 sentences:
"The credits will remain active as long as there is activity in the billing group. If there is 6 months of inactivity then users will be queried if the credits are still needed.​"

6) In the "Cloud Credits Request Form", under the question "Select your preferred analysis platform", there are questions for "Seven Bridges users only: Platform user name" and "Terra users only: Google identity". Under each of those fields is italicized text saying "Seven Bridges users only" and "Terra users only". In both cases the italicized text can be removed since it duplicates text already in the question.

Thanks!
Paul Kerr
BioData Catalyst Coordinating Center

**Comment by pkrenci** [comment]
Hi, there are some additional edits for the Cloud Credits webpage at:
[](https://biodatacatalyst.nhlbi.nih.gov/resources/cloud-credits)

This paragraph currently reads:

Users support their own cloud costs once they exceed their pilot funding. BioData Catalyst Powered by Terra can cover costs using their own Google accounts. Users of BioData Catalyst Powered by Seven Bridges can cover additional costs by providing a credit card or purchase order number. To support your own cloud costs on Seven Bridges, please contact support@sevenbridges.com. To support your own cloud costs on Terra, please contact support@terra.bio.

We'd like to add a couple of words and rearrange a couple of sentences so the new paragraph reads:

Users support their own cloud costs once they exceed their pilot funding. Users of BioData Catalyst Powered by Seven Bridges can cover additional costs by providing a credit card or purchase order number. Users of BioData Catalyst Powered by Terra can cover costs using their own Google accounts. To support your own cloud costs on Seven Bridges, please contact support@sevenbridges.com. To support your own cloud costs on Terra, please contact support@terra.bio.

Thanks,
- Paul

**Comment by mbwatson** [comment]
@pkrenci i see this has had an awaiting approval label for a while. is this still a desired change, and is it ready to go?

**Comment by pkrenci** [comment]
@mbwatson Yes these edits are still desired and are ready to go, thanks.

**Comment by mbwatson** [comment]
@pkrenci thanks -- we'll get this knocked out on Monday!

**Comment by suejinkim20** [comment]
@pkrenci changes are now up on staging. please verify everything looks correct before we merge to production. thanks!

**Comment by pkrenci** [comment]
@suejinkim20 The changes look correct. Thanks!

**Comment by pkrenci** [comment]
Hi @mbwatson, it looks like the additional edits requested on March 15 weren't included in this update, although they were updated on staging earlier this week. Thanks much.

**Comment by mbwatson** [comment]
@pkrenci thanks, sorry i closed this prematurely! these changes will be on prod shortly.

**Comment by mbwatson** [comment]
@pkrenci these changes are up on production now.

**Comment by pkrenci** [comment]
Thanks!
