### ISSUE TITLE
Anchor links not working on Fellows pages

### ISSUE THREAD

**Issue by alvoght-renci** [stagecc/bdc3-website-public#157]
Using the links (for names) at the top of the Fellows pages leads to their bio on the page, but using the link with their name as a web address just leads the user to the top of the page. 

Ie, using this link https://biodatacatalyst.nhlbi.nih.gov/fellows/cohort1#jean-monlong just goes to the top of Fellows Cohort 1 page. It should lead me to Jean's bio. 

I am using Google Chrome.

**Comment by mbwatson** [comment]
@scrummish this does not really use anchor links (this behavior is just kind of faked with javascript), but it probably should so that Fellows' profiles can be linked directly.
