### ISSUE TITLE
Links from Data page are unusable

### ISSUE THREAD

**Issue by pkrenci** [stagecc/bdc3-website-public#168]
Bug reported by BioData Catalyst user:

"Starting here - https://biodatacatalyst.nhlbi.nih.gov/resources/data

Then click Explore Studies or Explore COVID-19 Studies
URLS: https://biodatacatalyst.nhlbi.nih.gov/resources/data/studies, https://biodatacatalyst.nhlbi.nih.gov/covid-19

The tables on the resulting pages (one row per accession number) are unusable and completely break the page after one or two clicks. You can't type anything into the Filter area; the checkboxes don't do anything (what are they supposed to do?); etc."

**Comment by scrummish** [comment]
Hi @pkrenci can you check the https://biodatacatalyst.nhlbi.nih.gov/resources/data/studies page again to see if it is still giving you issues? The checkbox allows you to download a json or csv file of the selected data. It may have been breaking in an older build but it seems to be gone now. We were having table issues on another page recently but fixed that as well which may have fixed these tables issues as they don't seem to be a problem anymore.

**Comment by pkrenci** [comment]
Thank you @scrummish, it looks good and I've informed the user who reported the bug.
