### ISSUE TITLE
Add Links to BDC "Learn" Page

### ISSUE THREAD

**Issue by alvoght-renci** [stagecc/bdc3-website-public#177]
**Description**: Add the following links to the specified sections on https://biodatacatalyst.nhlbi.nih.gov/resources/learn/

**Documentation**
PIC-SURE Documentation: https://bdcatalyst.gitbook.io/biodata-catalyst-documentation/written-documentation/getting-started/explore-available-data/pic-sure-for-biodata-catalyst-user-guide 
 
**Videos**
PIC-SURE videos: https://www.youtube.com/watch?v=KQha_vZDgVc&list=PLJ6YccH8TEufZ5L-ctxzFF7vuZRLVacKw
 
**FAQs**
PIC-SURE FAQ's: https://bdcatalyst.gitbook.io/biodata-catalyst-documentation/written-documentation/getting-started/explore-available-data/pic-sure-for-biodata-catalyst-user-guide 
 
**Blogs & Tutorials**
PIC-SURE Tutorials: https://bdcatalyst.gitbook.io/biodata-catalyst-documentation/written-documentation/getting-started/explore-available-data/pic-sure-for-biodata-catalyst-user-guide/data-analysis-using-the-pic-sure-api

**Comment by mbwatson** [comment]
@alvoght-renci this change up on [staging](https://staging.biodatacatalyst.nhlbi.nih.gov/) for your review.

**Comment by alvoght-renci** [comment]
@mbwatson Looks perfect - let me know when it is live

**Comment by mbwatson** [comment]
@alvoght-renci done!
