### ISSUE TITLE
Show cohort 1 fellows abstracts

### ISSUE THREAD

**Issue by libcce** [stagecc/bdc3-website-public#2]
Develop hover/accordion feature to view fellows abstracts:
https://docs.google.com/spreadsheets/d/16Lb6-v73FzHg3YYELYjp75qZWdW_1A5iU-fJdVuz4ZA/edit?usp=sharing

The abstracts require editorial review.

Deadline of May 11.

**Comment by libcce** [comment]
Checking in... will a draft be available next week 5/4-8?

**Comment by mbwatson** [comment]
@libcce I think I can get that squared way by sometime next week. Are the abstracts proofread and finalized?

**Comment by mbwatson** [comment]
@libcce first stab at this here: https://staging.biodatacatalyst.nhlbi.nih.gov/fellows/cohort1/

i don't love the style, but it's a working prototype

**Comment by libcce** [comment]
Thanks @mbwatson we will review today and get back to you!

**Comment by libcce** [comment]
Design is good @mbwatson! We've asked the fellows to verify that the abstracts are correct for them, one last time. 

Is it possible to add direct (anchor) linking to specific fellows, so https://staging.biodatacatalyst.nhlbi.nih.gov/fellows/cohort1?fellow=brand as an example? If so, we identified this as a helpful feature.

**Comment by mbwatson** [comment]
We can do that. I'll probably going to steer away from query params for routing these views. I created a separate issue #10 to track adding those per-fellows views, and there's a question for you, @libcce .

**Comment by libcce** [comment]
Sorry, the example above was incorrect. We were thinking of an anchor tag and link like https://biodatacatalyst.nhlbi.nih.gov/fellows/cohort1#brand. So not to create individual profile views.

**Comment by mbwatson** [comment]
Is this something like what you envisioned: https://staging.biodatacatalyst.nhlbi.nih.gov/fellows/cohort1/ ?

**Comment by libcce** [comment]
Yes, that works!
