### ISSUE TITLE
Studies Table & MDS API integration

### ISSUE THREAD

**Issue by mbwatson** [stagecc/bdc3-website-public#242]
We aim to have a GitHub action that runs a Python script to generate JSON source files to populate the studies tables shown at https://biodatacatalyst.nhlbi.nih.gov/resources/data/studies/ and https://biodatacatalyst.nhlbi.nih.gov/covid-19. These files are consumed by Gatsby at build time to generate the data tables. We should be able to trigger action manually or by hitting an endpoint to execute the script, which will need slight modifications.

### script requirements (things the script will do)

- [x] retrieve all required fields from the MDS API
- [x] generate new source JSON files
  + `./data/studies/[studies|covid-studies].json`
  + on a new branch, `studies-update-<yyyy-mm-dd>`,
  + with the required fields: `code`, `study_id`, `full_name`, `short_name`, `study_description`
- [x] create a pull request, from `studies-update-<yyyy-mm-dd>` to `staging`

### additional requirements (things a human needs to do)

- [x] ensure the column definition files accommodate script changes (`./data/studies/[studies-columns|covid-studies-columns].json`)

**Comment by scrummish** [comment]
Staging is now set up to run a github action and commit the new data.

**Comment by mbwatson** [comment]
@scrummish, it doesn't look like the script fulfills the requirements listed above quite yet -- in particular, the PR piece. maybe [this](https://github.com/preventure/gh-action-create-pull-request) would be useful.
