### ISSUE TITLE
Extend Data Carousel Functionality

### ISSUE THREAD

**Issue by mbwatson** [stagecc/bdc3-website-public#254]
three types. details coming soon.

determine new models, provide constraints.

**Comment by suejinkim20** [comment]
@alvoght-renci Thank you for these helpful details! Could you advise on the timeline for this task? We are planning to tackle this when we come back from Thanksgiving break and are hoping to get some context for how to prioritize. Thank you so much!

**Comment by alvoght-renci** [comment]
@suejinkim20 Sorry, just saw your previous comment. I think the sooner, the better. We have data updates for the website that would use these new formats.

**Comment by mbwatson** [comment]
@suejinkim20 we'll scope this out in our already-scheduled meeting and bring a realistic timeline back to this conversation. then we can all compare notes, discuss what's possible in what time period, and set a goal.

**Comment by mbwatson** [comment]
@scrummish can you set up a deployment of this branch for @suejinkim20 to get feedback on this enhancement?

**Comment by alvoght-renci** [comment]
@suejinkim20 thank you, this is really helpful.

would you prefer to mark this issue as complete, and i can open a new issue when we have actual new cards to add?

**Comment by mbwatson** [comment]
i support that. this issue deals more with building the functionality. so, yeah, @suejinkim20 let's close this carousel extension issue, and then we can use a new one to track the carousel content update.
