### ISSUE TITLE
Update BDC Logo in Website Header

### ISSUE THREAD

**Issue by alvoght-renci** [stagecc/bdc3-website-public#260]
@suejinkim20 

BioData Catalyst is now a registered trademark, meaning the logo now has the registered trademark symbol in it. 

For this reason, it is asked to update the BDC website header with the new logo that has the registered trademark symbol. 

I have attached the logo in svg format, as this appears to be the format used on the website currently.

Of course, let me know if you have any questions!

![BDC_Logos_TM__STD-Regular-Color](https://user-images.githubusercontent.com/81979539/205071865-104811a1-6bf4-44d6-99a8-fa671d2af198.svg)

**Comment by alvoght-renci** [comment]
![BDC_Logos_TM__STD-Regular-Color](https://user-images.githubusercontent.com/81979539/206571015-0d32ce27-7899-47dc-8e9c-70c8de7d4374.svg)

Updated logo (horizontal line thinner)

**Comment by mbwatson** [comment]
it looks like this SVG could use some cleanup
![Screenshot from 2022-12-09 11-31-36](https://user-images.githubusercontent.com/6019870/206748263-41f2cc7e-bf14-4373-9306-84fbf8837416.png)

**Comment by mbwatson** [comment]
@alvoght-renci just checking in -- any update on this logo yet?

**Comment by alvoght-renci** [comment]
just checked in with josh - will keep you posted

**Comment by alvoght-renci** [comment]
fixed! 
![BDC_Logos_TM__STD-Regular-Color](https://user-images.githubusercontent.com/81979539/207958680-63518076-eb18-4221-95eb-edc46ae6e6ce.svg)

**Comment by Woozl** [comment]
Logo replaced and merged to `staging` branch!

**Comment by alvoght-renci** [comment]
looks great! consider closed.
