### ISSUE TITLE
Update BDC naming conventions on website

### ISSUE THREAD

**Issue by alvoght-renci** [stagecc/bdc3-website-public#271]
@mbwatson @Woozl 

BioData Catalyst has new naming conventions, which means we need to update the way "BioData Catalyst" is referenced on the website. We made a goal to have these changes implemented/live by March 1. 

The way the conventions work is a bit particular; ie, use X on first reference, Y on second reference, Z on subsequent references and this also all depends on if it is just BDC mentioned or if the mention is one of the BDC platforms. For this reason it might be likely there will have to be a manual replace rather than creating a script to do the work (just seems like too many outlier cases), but I don't know. **Of course I will identify the changes that need to be made and provide the usage of the new conventions and not just throw the style guide at you!** 

I think it would be ideal to find a time to meet and talk about the process for how we can implement this change! Note that I am working on making these same changes on our internal consortium website and could let you know the workflow we use for that, and see if it seems like a good fit for the website.

**Comment by alvoght-renci** [comment]
sounds good - we can figure out a time to meet via slack or email. earlier might be better, so just let me know when you want to start planning.

**Comment by alvoght-renci** [comment]
@suejinkim20 per a conversation i had with Steph, the Dug and HeLx pages should not be live on the BDC website. 

link to dug: https://biodatacatalyst.nhlbi.nih.gov/platforms/dug
link to helx: https://biodatacatalyst.nhlbi.nih.gov/platforms/helx

note that these pages are accessible via clicking an icon from the "platforms empowering our ecosystem" section of the [About > Overview](https://biodatacatalyst.nhlbi.nih.gov/about/overview) page. make sure that the logos/link to the page are removed from here as well.

additionally, remove the HeLx section from the Resources > Services page: https://biodatacatalyst.nhlbi.nih.gov/resources/services

**Comment by suejinkim20** [comment]
@alvoght-renci All changes have been implemented and are viewable at the staging site, including removing the two platform pages for dug and helx. Please let me know whether these changes are acceptable, and we will get these pushed to the main site!

**Comment by alvoght-renci** [comment]
@suejinkim20 these changes look great - thanks for the detailed and diligent work. please push to the main site!
