### ISSUE TITLE
Cohort 2 Call for Proposals

### ISSUE THREAD

**Issue by libcce** [stagecc/bdc3-website-public#28]
Update program (call for proposals) to cohort 2 program (call for proposals) per feedback from review committee, consortium, coordinating center. See https://github.com/stagecc/bdc3-website-public/pull/27

**Comment by mbwatson** [comment]
it feels a little off calling the Program page that when it is actually the Call for Proposals for the program. so it seems to me like there should be a separate view for these things such as (1) an "About (the Fellowship Program)" page, (2) a "Cohort 1" page, (3) a "Call for Proposals" page, and (4) the FAQs.

@libcce Is there enough content to warrant that expansion?

**Comment by libcce** [comment]
I thought the same @mbwatson . Let me check with the fellows team.

**Comment by mbwatson** [comment]
maybe something like this for the fellows subpages. closed bullets are pages, open bullets are items within those pages

#### Fellows
 + Overview
    * description of the program
    * goals of the program
    * maybe highlights, successes
    * link to various cohorts (only cohort 1 currently)
    * link to CFP
    * link to FAQs
 + Cohort 1
   * fellows w/ bios, projects
 + CFP
   * eligibility
   * financial stipend
   * timeline
   * application process
   * notification
   * questions
   * link to FAQs

**Comment by mbwatson** [comment]
@libcce is this issue (in its original form) different than #34?

**Comment by libcce** [comment]
This is now a different issue re: structuring the content. Speaking w/ Sarah, she asked if we can table this for now until after the cohort 2 application period. I recommend closing the issue as this is a known issue in the fellows team and we will get back. But feel free to keep it open if you want.
