### ISSUE TITLE
BDC Naming for External Links

### ISSUE THREAD

**Issue by alvoght-renci** [stagecc/bdc3-website-public#308]
@suejinkim20  I forgot to document that this pop up that appears when leaving the BDC site to external links. Replace instances in the pop up to "BDC" - I added text below for convenience, but I think there is just two changes that need to happen. Screenshot also included. 

**UPDATED TEXT**
> Leaving BDC
> 
> This graphic notice (  ) next to a link within the BDC ecosystem indicates that the link leads to another site that is not a federal government website.
> 
> NHLBI cannot attest to the accuracy of information provided on external websites.
> 
> Linking to a non-federal website does not constitute an endorsement by NHLBI of the sponsors or of the information and products presented on the website.
> 
> You will be subject to the destination's privacy policy when you follow the link.
> 
> Are you sure you want to navigate to this site?

**CURRENT POP UP**
![image](https://user-images.githubusercontent.com/81979539/223461993-19124548-9d43-4664-9832-3d1c843a7872.png)

**Comment by suejinkim20** [comment]
@alvoght-renci The requested change has been made and is live on the main site!
