### ISSUE TITLE
Create BDC Sitemap

### ISSUE THREAD

**Issue by alvoght-renci** [stagecc/bdc3-website-public#323]
@suejinkim20 A sitemap for the BDC website has been brought up/asked about recently. 

If it isn't too much trouble, it has been requested to have a current and complete BDC sitemap by COB Tuesday, 5/2. 

Although the BDC sitemap isn't extremely complex, let me know if I can be of any assistance given my knowledge of the site's navigation/structure (ie if you are totally overloaded with other work).

**Comment by suejinkim20** [comment]
@alvoght-renci 
Here is a google document that outlines the pages and most of the links on the BDC website: https://docs.google.com/document/d/1iTdOtN4aRFGg-s-vFdQmClwucGpUJHnU-HuXrQND4VU/edit#

I've also started a very basic visual sitemap here: https://miro.com/app/board/uXjVMMjWnUY=/?share_link_id=149150757813

**Comment by alvoght-renci** [comment]
@suejinkim20 Thanks for your work on this. The material is at a point that is considered complete/we can take it from here if any revisions are necessary. Awesome work per usual.
