### ISSUE TITLE
Updates/Functionality to BDC Blog Template

### ISSUE THREAD

**Issue by alvoght-renci** [stagecc/bdc3-website-public#380]
@suejinkim20 

- [x] Add functionality for graphics and media inline with text in blogs, with option for captions
- [x] Add author byline with published on date
- [x] Add "time to read"
- [x] Add block quote styling
- [x] Add September Blog Post

FUTURE: Researcher/Contributor highlight

**Comment by alvoght-renci** [comment]
@suejinkim20 

### Materials
Content for the September blog post on sickle cell disease can be found here: https://drive.google.com/drive/folders/1g9y_HrRuNmf8qVjjtoeJVcTowQ_2DbIw?usp=drive_link

The folder contains: 
- **Word doc** with the post itself, as well as the location in the article for the graphic (with accompanying caption and alt text) and pull quote
- Graphic for inclusion
- Headshots for the three contributors of the article

### Other Details
- Publish on Monday, September 11th - the earlier, the better
- Use the following URL: https://biodatacatalyst.nhlbi.gov/latest-updates/SCDdatasets2023 
- Let me know once it is live on staging and I will provide a review since it's the first time with the new template! (yay!)


Questions? Just let me know.

**Comment by mbwatson** [comment]
@suejinkim20 this looks done. can we close?

**Comment by suejinkim20** [comment]
Incorporate the following features into the Michelle Daya blog

# Image + Caption
![image (3)](https://github.com/stagecc/bdc3-website-public/assets/74567117/6eba93df-11e7-4ea0-a8bc-8de8cfb400b1)
Clinical characteristics.
1A) Breakdown of ancestry, disease group and genotyping platform across studies. 1B) Barplot of the total serum IgE IU/ml geometric mean by study, stratified by allergic/non-allergic group, colored by ancestry.
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8665111/figure/F1/

# Short Pull Quote
“One thing that is very important in science is reproducible research”
- Michelle Daya, Human Genetics Researcher

# Longer Pull Quote
Reflecting on her fellowship, Daya noted that without the data and analysis tools that BioData Catalyst provides, it would have been difficult to perform this type of research and it would have taken much longer.

**Comment by alvoght-renci** [comment]
@suejinkim20 Lauren has approved the "researcher template" format. Please retroactively update the Michelle Daya post on the live version of the website to include the new format.
