### ISSUE TITLE
Provide explanation of data in home page animation

### ISSUE THREAD

**Issue by libcce** [stagecc/bdc3-website-public#4]
From User Engagement Working Group, per the animation on the home page, where are these numbers coming from:

241,956 - Participants with phenotypes
73,223 - Participants

Is the 73,223 participants from working group studies?

Possible solution: Link to section on the site where this is explained.

**Comment by mbwatson** [comment]
I'm not sure where it comes from exactly. It was in with the rest of the site's content. This may not be issue-worthy.

**Comment by libcce** [comment]
Steph mentioned that @cmball1 assisted with the numbers in the homepage animation. Chris,  is there a place where we can tell users where that data comes from? Thanks in advance!

**Comment by cmball1** [comment]
@libcce The data is summarized from the files in this data manifest document: https://github.com/nhlbidatastage/Data-Manifest/blob/master/release-0/release_manifest.zip

The Data Manifest contains information on the VCF files from DBGap that are ingested into BDC. I would use the list of studies that we have VCF's for and mention it's all files from DBGap.

**Comment by joshbis** [comment]
I think that the simpler solution would be to add a qualifier to the 73,223. 

I assume that it is 73,223 with WGS (or whatever) that have been indexed on the platform.

**Comment by mbwatson** [comment]
closing because this will get addressed when the carousel takes advantage of the new extended functionality that was added by #254 .
