### ISSUE TITLE
Add bold text, link to text in Fellows FAQs "Still have questions?" section

### ISSUE THREAD

**Issue by libcce** [stagecc/bdc3-website-public#40]
On Fellows FAQ page, for the sentence below:

"Questions regarding the Fellows Program may be directed to the NHLBI BioData Catalyst Help Desk and by selecting the Fellows Program type from the contact form."

- Add bold/strong for "Fellows Program type" 
- Add "contact form" link https://staging.biodatacatalyst.nhlbi.nih.gov/contact

**Comment by mbwatson** [comment]
is this replacing the existing sentence?

**Comment by mbwatson** [comment]
probably don't bold "type" here, no?

**Comment by libcce** [comment]
I can go either way, but this maintains consistency where this information is presented in the CfP, FAQs.
