### ISSUE TITLE
Add help desk directory content and link to FAQ to contact page

### ISSUE THREAD

**Issue by libcce** [stagecc/bdc3-website-public#45]
Add information below to contact form page:

"BioData Catalyst Help Desk Directory 
Need help with where to direct your question? Please see the [help desk directory](https://bdcatalyst.freshdesk.com/support/solutions/articles/60000666868-where-do-i-direct-my-question-regarding-biodata-catalyst-and-the-help-desk-) to understand the best option for directing your request. "

Not able to directly link to FAQ on BDCatalyst, but it can be found at the bottom of:
https://biodatacatalyst.nhlbi.nih.gov/faqs/

Direct link to FAQ:
https://bdcatalyst.freshdesk.com/support/solutions/articles/60000666868-where-do-i-direct-my-question-regarding-biodata-catalyst-and-the-help-desk-
(if necessary, recommended HTML for embedded table in FAQ as well)

**Comment by mbwatson** [comment]
To be clear. the proposal is to add all of that to the Contact page or just the quoted content?

**Comment by libcce** [comment]
@mbwatson I'm looking to you regarding the best way to display this text to the user, before or after the form. The text to work with is in quotes.

**Comment by mbwatson** [comment]
Because this seems like instructions on how to correctly use the contact form, it feels like that text should be close to the field it clarifies. Thus I think that text should live as helper text in the form itself.

**Comment by libcce** [comment]
Help text is not available within the Freshdesk admin section for the feedback form.

My suggestion, add "Need help with where to direct your question? Please see the [help desk directory](https://bdcatalyst.freshdesk.com/support/solutions/articles/60000666868-where-do-i-direct-my-question-regarding-biodata-catalyst-and-the-help-desk-) to understand the best option for directing your request." after "Use the form below to let us know your questions or concerns." and close this out.

**Comment by mbwatson** [comment]
wow, that is a major oversight by freshworks and forces bad accessibility. adding the text to the top of the view now.

**Comment by mbwatson** [comment]
staged, awaiting approval: https://staging.biodatacatalyst.nhlbi.nih.gov/contact/
