### ISSUE TITLE
Bottom menu items obscured in mobile menu

### ISSUE THREAD

**Issue by mbwatson** [stagecc/bdc3-website-public#49]
![IMG_4785](https://user-images.githubusercontent.com/6019870/82454584-eca54680-9a7f-11ea-973c-060b715957a6.PNG)
This image shows bottom mobile menu items hidden from view. This is mobile Safari. This looks like an issue with how Safari handles overflow by default, but unsure.

**Comment by mbwatson** [comment]
the above tweak may work as a patch for these smaller screens running Safari.

**Comment by mbwatson** [comment]
@libcce this is not a fix, but a quick patch. can you check if this update helps the menu more usable on your phone?

**Comment by libcce** [comment]
Looks like it is fixed!
