### ISSUE TITLE
Add "How to cite us" to About page

### ISSUE THREAD

**Issue by libcce** [stagecc/bdc3-website-public#51]
Add section at the end of the About page:

**How to cite us**
If you wish to cite the BioData Catalyst ecosystem in your research, please use the following citation:

BioData Catalyst Consortium. (2020). The NHLBI BioData Catalyst. Zenodo. [http://doi.org/10.5281/zenodo.3822858](http://doi.org/10.5281/zenodo.3822858)

Also add "How to cite us" to the sub menu under "Data Protection".

This has been approved by Comms.

**Comment by mbwatson** [comment]
okey doke. first part is straight-forward. what is the sub menu under Data Protection?

**Comment by libcce** [comment]
Thanks @mbwatson! Regarding your 2nd questions, reworded, add "How to cite us" to the menu on the left under "Data Protection" and link it to the section.

**Comment by mbwatson** [comment]
ok, phew! i did that anyway, with the new section. will merge in tonight.
