### ISSUE TITLE
Issues with website functionality; page reloads required

### ISSUE THREAD

**Issue by wclenhardt** [stagecc/bdc3-website-public#53]
Issue with website requiring page reloads.

https://bdcatalyst.freshdesk.com/a/tickets/113

**Comment by mbwatson** [comment]
@wclenhardt thanks for logging this. i know _when_ this happens, and i sort of have a guess _why_ it happens.

when: if updates are pushed out between the time a user has the site open and when they click a link on the site, then the failure occurs.

why (maybe): my guess is that this has to do with how AWS/CloudFront/S3 points at the site files and those pointers change when it rebuilds, causing the failure users see.

@cmball1 and I discussed this this morning, and are continuing to investigate.

**Comment by cmball1** [comment]
@mbwatson Adding this for documentation purposes. I'll work on it this week.

It looks like 2 changes need to be made to how the files in S3 are handled. 
1. Change the `Cache-Control` that is added to the file in the AWS CodePipeline. Information on this header is detailed [here](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.9). I still need to work out the correct settings.
2. Add a lifecycle policy (see below) to the S3 bucket and add a tag to files that need to be deleted ('delete: true`). The lifecycle policy will remove the file when the file is older than 60 days and has the delete tag. Note: The 60 days is arbitrary and can be changed to whatever we want it to be. 
    * This includes writing a new Lambda function to use at the end of the CodePipeline that tags files with the delete tag in place of the current function that deletes the files. This Lambda function will need to be written in Node.js. @mbwatson I may need your help with this as I'm not very experienced with Node.js.

Lifecycle policy to add to S3 buckets:
```
<LifecycleConfiguration>
  <Rule>
    <ID>Soft-Delete</ID>
    <Filter>
       <Tag>
            <Key>deleted</Key>
            <Value>true</Value>
        </Tag>
    </Filter>
    <Status>Enabled</Status>
    <Expiration>
      <Days>60</Days>
    </Expiration>
  </Rule>
</LifecycleConfiguration>
```

Node.js code example of how to tag an S3 object [here](https://github.com/apancutt/deploy-aws-s3-cloudfront/blob/37d5b437fc6964c6edab2302f4ab39a1701689b4/src/deploy.js#L42)
More information about that code [here](https://www.npmjs.com/package/deploy-aws-s3-cloudfront#soft-deleting-objects)

Information on S3 [Object lifecycle management](https://docs.aws.amazon.com/AmazonS3/latest/dev/object-lifecycle-mgmt.html)

Potentially helpful if we use a GitHub action in place of AWS CodePipeline:
https://medium.com/trackstack/deploying-a-react-app-to-aws-s3-with-github-actions-b1cb9ba75c95

**Comment by mbwatson** [comment]
@cmball1 This is great! Thanks for looking into this issue. I would be happy to help on the Node side as much as possible. We can test this out with the pre-prod branch until we're sure it will work fully in production, too.

**Comment by cmball1** [comment]
@mbwatson Sorry for the delay. I added the lifecycle policy to the pre-prod S3 bucket and created a new lambda function `Tag_Delete_S3_files` to tag the files in place of the delete lambda function. If the files are older than 60 days and have the delete tag, the life cycle policy will delete them. 

I think the next step is to push some code to the pre-prod site with the website open to test if this resolves the loading issues. 

Do you have time to help test this out?

**Comment by mbwatson** [comment]
it's looking good. i've done two deployments to pre-prod without issue since this change. let's give it a few weeks longer to be sure.
