### ISSUE TITLE
Update study data information on Resources > Data page

### ISSUE THREAD

**Issue by libcce** [stagecc/bdc3-website-public#57]
On Resources > Data Page
https://biodatacatalyst.nhlbi.nih.gov/resources/data

Replace
"For more complete study information, download a detailed spreadhsheet using the link below."

With
"For more complete study information (TOPMed phs numbers with genomic data), download a detailed spreadsheet using the link below. The most recent data release notes are also available using the link below."

Link to "Release Notes"
https://bdcatalyst.gitbook.io/biodata-catalyst-documentation/biodata-catalyst-release-notes/2020-04-02-biodata-catalyst-ecosystem-release-notes

There are two "links below" so we should probably qualify both with "using the Download Study Details link below" and "using the Release Notes link below".

**Comment by mbwatson** [comment]
this is a good change. in addition, though, may i suggest a slightly different approach? i was thinking something like this:

![Screenshot from 2020-06-13 12-48-27](https://user-images.githubusercontent.com/6019870/84574485-b2744f80-ad74-11ea-8b50-f758190ec18a.png)

i don't think it's terribly useful to explicitly tell the user to click the "download this thing link" to "download this thing." with this, it's clear which link to click and what to expect when clicking each of the links, based on their text. this is in staging to see it.

i know i'm not the copy editor, but if it were really up to me, i would even consolidate this a bit more still and say something along the lines of "Download BioData Catalyst Release Notes and Study Details (TOPMed phs numbers with genomic data) are available to download below."

**Comment by stephsuber** [comment]
I like the download boxes. 

Text above them could say:
"Download BioData Catalyst Release Notes and Study Details (TOPMed phs numbers with genomic data) below."

@libcce what do you think of that?

**Comment by libcce** [comment]
Looks good @stephsuber! Thanks both!
