### ISSUE TITLE
Safari/Mac OS choppy website scrolling

### ISSUE THREAD

**Issue by libcce** [stagecc/bdc3-website-public#60]
From the help desk: Website scrolling is very choppy when using Safari (MacOS) — appears to be something to do with the floating honeycomb background. This seems to be less of an issue with Chrome.

Safari 13.1  Mac OS 10.15.4

**Comment by mbwatson** [comment]
This will be extremely hard to diagnose and test without more details and without Max OS running safari. @libcce Do you have these same setup, and do you experience this issue? If so, maybe you wouldn't mind troubleshooting with me.

**Comment by mbwatson** [comment]
I'm going to close this in lieu of #48 , which is certainly tied to the same animation performance issues in WebKit as this.
