### ISSUE TITLE
Update Seven Bridges Documentation Links to GitBook

### ISSUE THREAD

**Issue by libcce** [stagecc/bdc3-website-public#64]
Update Seven Bridges Documentation links on:
https://biodatacatalyst.nhlbi.nih.gov/resources/services
https://biodatacatalyst.nhlbi.nih.gov/resources/learn

to:
https://bdcatalyst.gitbook.io/biodata-catalyst-documentation/analyze-data/seven-bridges

**Comment by mbwatson** [comment]
staged. this fix will go out in today's production deployment.
