### ISSUE TITLE
Add fields to Cloud Credits Request Form

### ISSUE THREAD

**Issue by libcce** [stagecc/bdc3-website-public#67]
All fields in bold below are currently included in the form and do not need to be added. Fields that are not in bold need to be added with the exception of Platform/Service where the only change will be adding the word "Preferred" before "Platform/Service". New fields have been added to Freshdesk > Ticket Fields w/ "Cloud Credits" prefix. Please arrange the fields according to the order/sequence below as well.

- **Your Name**
- **Email Address**
- Role (this is the Title field in Freshdesk)
- Organization (this is the Company/Organization field in Freshdesk)
- PI, Collaborator, Student Information
List Name(s), Email(s), Role(s), Organization(s)
- Project Name & Description (1000 characters, same language as justification)
- **Justification for Credits**
- **Estimate of Cloud Credits Needed**
- Preferred Platform/Service (only change her is that preferred has been added)

All fields are required

Leave on staging for review. Deadline: Morning, Aug 19.

**Comment by mbwatson** [comment]
@libcce I'm only getting the following fields to submit:

ticket_type,
subject,
requester,
source,
status,
priority,
group,
agent,
description,
company,
cf_estimated_cloud_credits_requested,
cf_what_bdcatalyst_service_will_you_use,
cf_justification_for_credits,
cf_cloud_credits_collaborator_information,
cf_cloud_credits_project_namedescription,
cf_name,

I assume by, "Compacy/Organization," you mean the "company" field. What is the Title field?

**Comment by libcce** [comment]
Additional field to add:
Cloud Credits: Previous Request (has been added as a new field in Freshdesk)
Add the new field above Project Name & Description

Field to modify:
Extend the size/length of the Contributors field (similar to Project Name & Description) and rename to Collaborators.

**Comment by libcce** [comment]
Remove the "Cloud Credits: Previous Request" field, from Freshdesk and the form per CCTT meeting feedback. 

Still requested via CCTT, modify the Contributors field:
Extend the size/length of the Contributors field (similar to Project Name & Description) and rename to Collaborators.
