### ISSUE TITLE
Cloud Credits Page: Add content under header, before request form

### ISSUE THREAD

**Issue by libcce** [stagecc/bdc3-website-public#68]
Add the following content under the "Cloud Credits" header:

There is no charge for the storage of the data that is already available in the ecosystem. Costs are incurred for computation, the storage of derived results, and the storage of any new data uploaded to the BioData Catalyst ecosystem. An initial $500 credit is allocated to each ecosystem project account. Should more credit be needed, please use the Cloud Credit Request Form below and follow these instructions:
 
- Enter your name, email, role, and organization as the primary requestor.
- List project PI, collaborator, student name(s), email(s), role(s), organization(s).
- Provide the project name and a brief (1000 characters or less) project description.
- Include a brief (3000 characters or less) description/justification of what the credits will be used for. Reviewers will be interested in the following information: 
  - Significance and goals of the project
  - Datasets, tools, types of analysis to be used 
  - Experience using cloud platforms
  - Anticipated timeline for the work
- Add an estimate of cloud credits needed (in US Dollars). Round up to the nearest $100 and add a $300 buffer for troubleshooting and testing. 
- Indicate the preferred platform/service (BioData Catalyst powered by [Terra](https://biodatacatalyst.nhlbi.nih.gov/platforms/terra) or [Seven Bridges](https://biodatacatalyst.nhlbi.nih.gov/platforms/seven-bridges)) that will be used.
 
Information on understanding cloud costs can be found below with additional guidance forthcoming:
 
[Controlling your cloud costs](https://bdcatalyst.gitbook.io/biodata-catalyst-documentation/analyze-data/terra/controlling-cloud-costs) (BioData Catalyst powered by Terra) 
[Cloud cost benchmarking information in Public Apps Gallery](https://platform.sb.biodatacatalyst.nhlbi.nih.gov/resources/public-gallery/apps) (BioData Catalyst powered by Seven Bridges)
 
NHLBI will review the request and respond as soon as possible.

Then include the Cloud Credits Request Form here...

Post and leave in staging until reviewed. Deadline: Morning, Aug 19.

**Comment by libcce** [comment]
Add Cloud Credits to Resources drop down nav menu. If you want to keep to one word, Credits should be sufficient.

**Comment by libcce** [comment]
Replace the current text under the "Cloud Credits" header up to the form with:

## Cloud Costs on BioData Catalyst

Users can incur cloud costs on the BioData Catalyst workspace environments, Seven Bridges and Terra, and these cloud costs include both computation and storage.  When users perform analyses on Seven Bridges and Terra, this leads to computation costs based on the size of the AWS or Google compute instance that is used and the duration for which it is used. Performing an analysis creates results files, or derived data. These derived data are stored on BioData Catalyst cloud storage buckets and incur costs based on the file size and the length of time the file is stored. Users can delete result files once they are no longer needed to avoid unnecessary storage costs. In addition to running computation on the hosted datasets, BioData Catalyst users have the option to upload/import their own data to the system. Users incur storage costs for these uploaded files as well. 

## Pilot Funding

NHLBI encourages new users to test and evaluate BioData Catalyst for their research needs by offering each $500 in cloud credits. The $500 allows new users to test their pipelines on smaller samples, before scaling up, and estimating how much full analysis will cost. If the anticipated costs are in excess of $500, users can apply for additional credits via the NHLBI BioData Catalyst Cloud Credit Program (see form below).

## NHLBI BioData Catalyst Cloud Credit Program

The NHLBI BioData Catalyst Cloud Credit Program offers researchers the opportunity to apply for cloud credits to support research projects in the heart, lung, blood, and sleep fields. Cloud credits are awarded on a per project basis, so if multiple researchers are working together on a larger project, the group should submit one application. All individuals involved in the project will be able to make use of awarded cloud credits through a shared billing group on either Seven Bridges or Terra. Researchers can submit an application using the Cloud Credit Request Form below. As part of the application, an estimate of the total cost of the project is needed. 

## Cloud Credit Request Form Instructions

If you are requesting additional cloud credits, provide your name, email, role and organization and list information about your collaborators (PI, collaborator, student name(s), email(s), role(s), organization(s)). If you have submitted a previous request, please indicate yes or no. Include a project name and a brief (1000 characters or less) project description. Prepare a brief (3000 characters or less) description/justification of what the credits will be used for. Reviewers will be interested in the following information:

- Significance and goals of the project
- Datasets, tools, types of analysis to be used
- Experience using cloud platforms
- Anticipated timeline for the work

Add an estimate of cloud credits needed (in US Dollars). Round up to the nearest $100 and add a $300 buffer for troubleshooting and testing. Indicate the preferred platform/service (BioData Catalyst powered by Terra or Seven Bridges) that will be used.

## Understanding Cloud Costs

Information on understanding cloud costs can be found below with additional guidance forthcoming:

- [Controlling your cloud costs](https://bdcatalyst.gitbook.io/biodata-catalyst-documentation/analyze-data/terra/controlling-cloud-costs) (BioData Catalyst powered by Terra)
- [Cloud cost benchmarking information in Public Apps Gallery](https://platform.sb.biodatacatalyst.nhlbi.nih.gov/resources/public-gallery/apps) (BioData Catalyst powered by Seven Bridges)

Requests for additional cloud credits will be reviewed and decided as soon as possible.

**Comment by mbwatson** [comment]
see new updates in an email
