### ISSUE TITLE
Update Release Notes button link

### ISSUE THREAD

**Issue by libcce** [stagecc/bdc3-website-public#69]
Update Release Notes button link on the Data page to:
https://bdcatalyst.gitbook.io/biodata-catalyst-documentation/biodata-catalyst-release-notes
Which (should) direct to the latest release notes:
https://bdcatalyst.gitbook.io/biodata-catalyst-documentation/biodata-catalyst-release-notes/2020-08-24-biodata-catalyst-ecosystem-release-notes

**Comment by libcce** [comment]
Also, update the Release Notes link on the Services page under Documentation to:
https://bdcatalyst.gitbook.io/biodata-catalyst-documentation/biodata-catalyst-release-notes

**Comment by mbwatson** [comment]
> Also, update the Release Notes link on the Services page under Documentation to:
> https://bdcatalyst.gitbook.io/biodata-catalyst-documentation/biodata-catalyst-release-notes

Do you mean on the Learn page?
