### ISSUE TITLE
Update Content on Gen3 Learn Page

### ISSUE THREAD

**Issue by libcce** [stagecc/bdc3-website-public#70]
Gen3 has submitted update language for their "Learn" page:
https://biodatacatalyst.nhlbi.nih.gov/platforms/gen3

Comms will need to review the submitted content below.

Gen3's submitted new text:

About Gen3

The Gen3 software platform enables the standing-up of data commons by providing authentication/authorization, object file indexing, interactive data search and export, and analytical workspaces services. Partner organizations and approved researchers can access and search over hosted genomic and phenotypic data, and export selected cohorts to analytical workspaces in a scalable, reproducible, and secure manner.

Key Features

- Authentication (AuthN) and authorization (AuthZ) services that utilize OpenID Connect flow to generate tokens for clients. The service supports Identify Providers (IDPs) including Google and NIH iTrust

- Indexing service that automatically assigns permanent digital IDs, or globally unique identifiers (GUIDs), to object files. These IDs can be used to retrieve data or query the metadata associated with the object

- An interactive data exploration portal that allows users to search and filter through study-specific clinical and genomic data. Users can export their selected cohorts to analytical workspaces

- Lightweight workspaces that allow users to run analytical tools and applications such as Jupyter notebooks and RStudio

**Comment by stephsuber** [comment]
Please put a period at the end of each of the key features. Otherwise this looks good to me from a comms perspective. @libcce please review for the tech content and then we're good to go!

**Comment by libcce** [comment]
@stephsuber I made the same changes on my end and also updated some of the text. @mbwatson This is ready to update. Thanks!

Updated content below:


About Gen3

The BioData Catalyst powered by Gen3 platform provides data commons services through authentication/authorization, object file indexing, interactive data search and export, and analytical workspaces services. Partner organizations and approved researchers can search and access hosted genomic and phenotypic data, and export selected cohorts to analytical workspaces in a scalable, reproducible, and secure manner.

Key Features

- Authentication (AuthN) and authorization (AuthZ) services that utilize OpenID Connect flow to generate tokens for clients. The service supports Identify Providers (IDPs) including Google and NIH iTrust.

- Indexing service that automatically assigns permanent digital IDs, or globally unique identifiers (GUIDs), to object files. These IDs can be used to retrieve data or query the metadata associated with the object.

- An interactive data exploration portal that allows users to search and filter through study-specific clinical and genomic data. Users can export their selected cohorts to analytical workspaces.

- Workspaces that allow users to run analytical tools and applications such as Jupyter notebooks and RStudio.

**Comment by mbwatson** [comment]
Done!

**Comment by libcce** [comment]
Still looks like the old text
https://biodatacatalyst.nhlbi.nih.gov/platforms/gen3

**Comment by mbwatson** [comment]
Refresh?
