### ISSUE TITLE
Required Fields - Cloud Credit Requests Form

### ISSUE THREAD

**Issue by libcce** [stagecc/bdc3-website-public#78]
Cloud Credit Request form does not indicate to user that all fields are required:
https://biodatacatalyst.nhlbi.nih.gov/resources/cloud-credits/

Suggestion:
Include "* All Fields Required. If the field does not apply or the answer is not known, add N/A." at the top of the form. Add asterisk next to all the field labels. 

Suggestion:
When form submitted, and certain fields are not completed, highlight the fields that are required instead of one at a time like the current form uses.

**Comment by mbwatson** [comment]
I'll go ahead and add a _required fields_ note. As for the highlighting, I think that's a browser-specific thing. For example, Chrome walks users through invalid fields one-at-a-time (undesirable, I know), while Firefox will highlight all fields failing validation (non-empty in this case). See this screenshot taken after attempting to submit an empty form.

![Screenshot_2020-11-25 Cloud Credits](https://user-images.githubusercontent.com/6019870/100275855-959c9480-2f2e-11eb-9f81-602c017b4f39.png)

You're using Chrome I'm guessing?

I can look into overriding default browser behavior here.

**Comment by libcce** [comment]
Yes, I'm using Chrome. The message that appears at the top of the browser is "Please fill in the field" but it is not aligned with the highlighted field. The message appears at the very top of the page, under the COVID-19 banner.

**Comment by mbwatson** [comment]
That sounds interesting. Can you share a screenshot?

**Comment by mbwatson** [comment]
i'm going to close this due to inactivity.
