### ISSUE TITLE
Add sentence to Cloud Credits page

### ISSUE THREAD

**Issue by libcce** [stagecc/bdc3-website-public#80]
Add the following sentence to the Cloud Credits page, before the sentence "If you need additional assistance with understanding cloud cost...":

For community guidance on estimating cloud credits, please see feedback from users in the following [BioData Catalyst Forum post](https://bdcatalyst.freshdesk.com/support/discussions/topics/60000405803).

**Comment by mbwatson** [comment]
done, thanks!
