### ISSUE TITLE
Content edit to the Cloud Credits page

### ISSUE THREAD

**Issue by stephsuber** [stagecc/bdc3-website-public#81]
Please add 

[Tips for estimating cloud credits (user-generated)](https://bdcatalyst.freshdesk.com/support/discussions/topics/60000405803) to [this page](https://biodatacatalyst.nhlbi.nih.gov/resources/cloud-credits) as a final bullet in the “Understanding Cloud Costs” section.

**Comment by libcce** [comment]
@stephsuber @mbwatson has already made this update, see "For community guidance on estimating cloud credits, please see feedback from users in the following BioData Catalyst Forum post." on the same page.
