### ISSUE TITLE
New content for About/How to Cite Us section

### ISSUE THREAD

**Issue by libcce** [stagecc/bdc3-website-public#83]
On About, under [How to Cite Us](https://biodatacatalyst.nhlbi.nih.gov/about#citation)...

Please remove:

"If you wish to cite the BioData Catalyst ecosystem in your research, please use the following citation:

BioData Catalyst Consortium. (2020). The NHLBI BioData Catalyst. Zenodo. http://doi.org/10.5281/zenodo.3822858"

and replace with:

"To learn more about citing and acknowledging BioData Catalyst, [visit our documentation](https://bdcatalyst.gitbook.io/biodata-catalyst-documentation/biodata-catalyst-glossary/citation-and-acknowledgement)."

**Comment by mbwatson** [comment]
[staged](https://staging.biodatacatalyst.nhlbi.nih.gov/about/) this change.

![Screenshot_2021-01-05 About BioData Catalyst](https://user-images.githubusercontent.com/6019870/103671384-d4b7ff80-4f48-11eb-9c6f-04b719a31e73.png)

will push out to prod later today if there are no additional changes.
