### ISSUE TITLE
Edits to the data page

### ISSUE THREAD

**Issue by stephsuber** [stagecc/bdc3-website-public#84]
Please add:

COVID-19 data ([ORCHID](https://biodatacatalyst.nhlbi.nih.gov/covid-19)) to the bottom of the list under "The BDCat ecosystem currently hosts a number of..."

Also please add:

A button between the two already there ("Explore Studies" and "Release Notes") that says Explore COVID-19 Studies and link to https://biodatacatalyst.nhlbi.nih.gov/covid-19

Would like to see this on staging before pushing live so I can get final approval from the team. Thanks!

**Comment by mbwatson** [comment]
currently staged: https://staging.biodatacatalyst.nhlbi.nih.gov/resources/data

**Comment by stephsuber** [comment]
This version is good, but we need two more tiny changes:

1. Please change the sentence above the CTA boxes to say "Download BioData Catalyst Release Notes and Study Details via the boxes below."
2. Remove at least one space between that sentence and the CTA boxes. We would like it to look more like they are in the same section. 

Would like to see via staging again once more before we go live. Thanks!

**Comment by mbwatson** [comment]
@stephsuber these changes are staged: https://staging.biodatacatalyst.nhlbi.nih.gov/resources/data

**Comment by stephsuber** [comment]
Thanks, Matt. All looks good. Let's publish!
