### ISSUE TITLE
Update data numbers on the home page

### ISSUE THREAD

**Issue by stephsuber** [stagecc/bdc3-website-public#85]
Bo, please change the data numbers on the home page to be:

Participants - 406,853
Petabytes of Data - 3.42
Participants with phenotypes - 285,093

Also, please change this sentence (BioData Catalyst provides one point of entry to the most TOPMed datasets, including Freeze 5b data) to become this sentence (BioData Catalyst provides one point of entry to the most TOPMed datasets, including Freeze 8 data.)

**Comment by connectbo** [comment]
Stephanie, the homepage data numbers/cloud-credit data are changed in this commit.

**Comment by mbwatson** [comment]
thanks @connectbo !
