### ISSUE TITLE
Indicate whether user is currently authenticated

### ISSUE THREAD

**Issue by libcce** [stagecc/bdc3-website-public#9]
When a user clicks on the consortium member login button they are sent to another site to log in while the button on the previous page does not indicate they are logged in. Suggestion from user that this should be a link instead to indicate you are leaving the BD Catalyst site.

**Comment by mbwatson** [comment]
the title and comment don't seem like the same issue.

- addressing the title: we'd need to perform a second auth handshake with the consortium member site
- addressing your comment: notifying the user that you're leaving the catalyst site is something that is already in development and should be resolved soon.

**Comment by libcce** [comment]
Title and comment are the same issue. Please reword if you would like.

The user was confused why the button did not indicate that they were logged in once they had logged in via the other site. After discussion with the user, they thought that a link might be best vs a button (button indicates that you are entering a system vs a link visiting another page/site). As you say, the "you are now leaving BD Catalyst" message might help here?

**Comment by mbwatson** [comment]
One useful place to show this information is on the consortium LOGIN call to action in the footer, although this could be elevated and known site-wide.

**Comment by mbwatson** [comment]
Because there's no benefit from this site knowing you've logged in on that site, I'd guess this is far from priority. I do agree that the button saying "Login" is a little misleading, so I propose a more generic link to the consortium site with different text.

**Comment by mbwatson** [comment]
this commit removes the login text: https://github.com/stagecc/bdc3-website-public/commit/0f23e601f774951736888ef56b7196ccc773dc0d
