### ISSUE TITLE
Update Data Management Strategy URL on BDCatalyst Website 

### ISSUE THREAD

**Issue by tmadden24** [stagecc/bdc3-website-public#91]
Hello -- Please update the Data Management Strategy link at the bottom of the Data page (https://biodatacatalyst.nhlbi.nih.gov/resources/data) to the following: https://bdcatalyst.gitbook.io/biodata-catalyst-documentation/biodata-catalyst-data-management-strategy

**Comment by mbwatson** [comment]
i've staged this change: https://staging.biodatacatalyst.nhlbi.nih.gov/resources/data/

@tmadden24 please verify it's correct, and we'll get that into the production site this evening

**Comment by tmadden24** [comment]
Perfect, thanks @mbwatson !
