### ISSUE TITLE
Terra links on BioData Catalyst website need to be updates before 10 am Monday, 3/1

### ISSUE THREAD

**Issue by stephsuber** [stagecc/bdc3-website-public#92]
Please update the links [in this spreadsheet](https://docs.google.com/spreadsheets/d/1ZSZ8gQO1LvPUWq5FXMuz_R3iekgO5gZX9JuDmoS47RI/edit?usp=sharing) on the website so that the Terra demo will work for Monday's presentation to Fellows.

**Comment by mbwatson** [comment]
i'm on it!
