### ISSUE TITLE
Update URLs on BDCatalyst Resources --> Data Page

### ISSUE THREAD

**Issue by tmadden24** [stagecc/bdc3-website-public#98]
There are a few broken links on https://biodatacatalyst.nhlbi.nih.gov/resources/data/ that need to be updated. I think I've included the correct links below:

- Release Notes download box/link (https://bdcatalyst.gitbook.io/biodata-catalyst-documentation/written-documentation/release-notes) 

- Data Management Strategy link at the bottom of the page (https://bdcatalyst.gitbook.io/biodata-catalyst-documentation/data-management/data-management-strategy) 

- Data Generators Guidance link at the bottom of the page (https://bdcatalyst.gitbook.io/biodata-catalyst-documentation/data-management/biodata-catalyst-data-generator-guidance)

**Comment by mbwatson** [comment]
@tmadden24 these changes should be live in a few minutes!
